### ISSUE TITLE
ImportError: Please make sure you have pycuda installed

### ISSUE THREAD

**Issue by nguptaHQ** [chybhao666/TensorRT#1]
After setup of docker, I am trying to import tensorrt:

>>> import tensorrt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/tensorrt/__init__.py", line 77, in <module>
    from tensorrt import infer, parsers, utils, lite, plugins
  File "/usr/lib/python2.7/dist-packages/tensorrt/lite/__init__.py", line 54, in <module>
    from .engine import Engine
  File "/usr/lib/python2.7/dist-packages/tensorrt/lite/engine.py", line 60, in <module>
    raise ImportError("""Please make sure you have pycuda installed""")
ImportError: Please make sure you have pycuda installed
>>> 

I am able to import pycuda

>>> import pycuda
>>> 

Please look into the issue

**Comment by nguptaHQ** [comment]
I got this error after fresh setup of docker container.

root@60b84d6d4c7a:/workspace# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorrt
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/tensorrt/__init__.py", line 77, in <module>
    from tensorrt import infer, parsers, utils, lite, plugins
  File "/usr/lib/python2.7/dist-packages/tensorrt/infer/__init__.py", line 54, in <module>
    from ._infer_enums import *
  File "/usr/lib/python2.7/dist-packages/tensorrt/infer/_infer_enums.py", line 54, in <module>
    from tensorrt.infer import _nv_infer_bindings as nvinfer
ImportError: numpy.core.multiarray failed to import

Then i upgraded the numpy. Then I am getting pycuda issue.

Please look into issue and help

**Comment by webbrain-one** [comment]
Thanks for reporting! I opened a PR to fix this: https://github.com/chybhao666/TensorRT/pull/3. It updates the import handling so `import tensorrt` works correctly when `pycuda` is installed, resolving the confusing `ImportError: Please make sure you have pycuda installed`.
